[project]
name = "adventofcode2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "adventofcode>=25.0",
    "numpy>=2.3.5",
    "scipy>=1.16.3",
    "z3-solver>=4.8.17",
    "shapely>=2.1.2",
    "z3>=0.2.0",
]
